#!/bin/bash
printf '%o' $(( $(echo $WATER | tr 'water' '01234' | python3 -c "print(int(input(),5))") + $(echo $STIR | tr 'stir.' '01234' | python3 -c "print(int(input(),5))") )) | tr '01234567' 'bestchol'
